[versions]
kotlin = "2.1.20"
dokka = "2.0.0"
mavenPublish = "0.34.0"

mockwebserver = "5.1.0"
commonsText = "1.13.1"
snakeyaml = "2.4"

assertj = "3.27.3"
mockitoKotlin = "5.4.0"
mockitoCore = "5.12.0"
junit = "4.13.2"
equalsverifier = "3.19.3"
jacoco = "0.8.13"

[libraries]
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version.ref = "mockwebserver" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
